insert into rating.config(property,property_value) select 'STATISTICS_FORMAT','100' from dual
where not exists (select 1 from rating.config c where c.property = 'STATISTICS_FORMAT');

insert into rating.rating_score(name,score) select '表现突出',5 from dual
where not exists (select 1 from rating.rating_score s where s.name = '表现突出');
insert into rating.rating_score(name,score) select '表现较好',4 from dual
where not exists (select 1 from rating.rating_score s where s.name = '表现较好');
insert into rating.rating_score(name,score) select '表现一般',3 from dual
where not exists (select 1 from rating.rating_score s where s.name = '表现一般');
insert into rating.rating_score(name,score) select '表现较差',2 from dual
where not exists (select 1 from rating.rating_score s where s.name = '表现较差');
insert into rating.rating_score(name,score) select '表现很差',1 from dual
where not exists (select 1 from rating.rating_score s where s.name = '表现很差');
insert into rating.rating_score(name,score) select '表现极差',0 from dual
where not exists (select 1 from rating.rating_score s where s.name = '表现极差');

insert into rating.rating_supp_options(name,category,code) select '本年度工作统计','BXDF','62e7d685-de66-4b85-b401-b5c69c836030' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '62e7d685-de66-4b85-b401-b5c69c836030');
insert into rating.rating_supp_options(name,category,code) select '技术或工艺改进','BXDF','eadb13de-f617-4f4f-8c3c-9f755ddc663c' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = 'eadb13de-f617-4f4f-8c3c-9f755ddc663c');
insert into rating.rating_supp_options(name,category,code) select '责任心','BXDF','f8bd4c60-c4cd-40a4-b13a-a8349bf66a24' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = 'f8bd4c60-c4cd-40a4-b13a-a8349bf66a24');
insert into rating.rating_supp_options(name,category,code) select '协作精神','BXDF','7ccafc20-d860-4adc-8ad0-5f926a56bf61' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '7ccafc20-d860-4adc-8ad0-5f926a56bf61');
insert into rating.rating_supp_options(name,category,code) select '劳动纪律','BXDF','cf84cd1d-62c4-433a-9b08-f85cd25c20e5' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = 'cf84cd1d-62c4-433a-9b08-f85cd25c20e5');
insert into rating.rating_supp_options(name,category,code) select '规范操作','BXDF','b7f8079c-8310-461c-ae4c-c63eb63dc9f6' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = 'b7f8079c-8310-461c-ae4c-c63eb63dc9f6');
insert into rating.rating_supp_options(name,category,code) select '事件汇报','BXDF','72cece1e-09ad-4bb9-9c7c-32465412da4e' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '72cece1e-09ad-4bb9-9c7c-32465412da4e');
insert into rating.rating_supp_options(name,category,code) select '安全保密','BXDF','7d51f7da-02e4-4850-b71a-996661f8861a' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '7d51f7da-02e4-4850-b71a-996661f8861a');
insert into rating.rating_supp_options(name,category,code) select '完成任务情况','NLDF','3aeb5d80-ec23-46c2-b24e-d3f9a05ab076' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '3aeb5d80-ec23-46c2-b24e-d3f9a05ab076');
insert into rating.rating_supp_options(name,category,code) select '解决问题能力','NLDF','f63773ea-cc76-4ede-af42-46285ba0959a' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = 'f63773ea-cc76-4ede-af42-46285ba0959a');
insert into rating.rating_supp_options(name,category,code) select '学习和应用新技术','NLDF','2d1b01c9-e9e6-40d6-b1ec-d4517d6298a7' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '2d1b01c9-e9e6-40d6-b1ec-d4517d6298a7');
insert into rating.rating_supp_options(name,category,code) select '分析统计能力','NLDF','50df5443-e051-4bef-916c-9994f9ee9859' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '50df5443-e051-4bef-916c-9994f9ee9859');
insert into rating.rating_supp_options(name,category,code) select '组内完成任务情况','WCRWQK','1e50cb11-8e7f-475c-9099-ed439e8674ad' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '1e50cb11-8e7f-475c-9099-ed439e8674ad');
insert into rating.rating_supp_options(name,category,code) select '组内工艺质量与控制','WCRWQK','1c4abcae-e1e1-4605-b5b2-996f0829e7e7' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '1c4abcae-e1e1-4605-b5b2-996f0829e7e7');
insert into rating.rating_supp_options(name,category,code) select '组内技术发展','WCRWQK','cc38460e-6ffa-469e-b44c-2cc03115c926' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = 'cc38460e-6ffa-469e-b44c-2cc03115c926');
insert into rating.rating_supp_options(name,category,code) select '室内外协作','ZZNL','a8a10a0c-9195-40c9-bb11-c410ab611372' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = 'a8a10a0c-9195-40c9-bb11-c410ab611372');
insert into rating.rating_supp_options(name,category,code) select '实验室管理','ZZNL','5994e4cd-6de9-473a-a199-c91c94073222' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '5994e4cd-6de9-473a-a199-c91c94073222');
insert into rating.rating_supp_options(name,category,code) select '培养人才','ZHNL','c63727b6-4e57-4b9d-9d51-cc8a90d9f72c' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = 'c63727b6-4e57-4b9d-9d51-cc8a90d9f72c');
insert into rating.rating_supp_options(name,category,code) select '实验室建设','ZHNL','178d2802-8e54-460c-9fa3-a29b0377c4c8' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '178d2802-8e54-460c-9fa3-a29b0377c4c8');
insert into rating.rating_supp_options(name,category,code) select '本人研究任务完成情况','ZHNL','fd49cfcf-2d6e-423b-b36a-27b05b6a5b30' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = 'fd49cfcf-2d6e-423b-b36a-27b05b6a5b30');
insert into rating.rating_supp_options(name,category,code) select '本人解决的关键技术','ZHNL','06ade6a9-12f5-417c-b161-cdc59519b8ed' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '06ade6a9-12f5-417c-b161-cdc59519b8ed');
insert into rating.rating_supp_options(name,category,code) select '本人工作亮点','ZHNL','3cd9360d-9e97-4eb3-b6b8-85966abc2673' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '3cd9360d-9e97-4eb3-b6b8-85966abc2673');
insert into rating.rating_supp_options(name,category,code) select '文章专利与报告','ZHNL','fa428765-09d0-478e-902d-acbe2947e4ae' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = 'fa428765-09d0-478e-902d-acbe2947e4ae');
insert into rating.rating_supp_options(name,category,code) select '安全与保密','ZHNL','6bead800-3481-4e5a-9fd3-1b89b93b105b' from dual where not exists (select 1 from rating.rating_supp_options t where t.code = '6bead800-3481-4e5a-9fd3-1b89b93b105b');

insert into rating.rating_supp_template(code,name) select 'A','A' from dual
where not exists (select 1 from rating.rating_supp_template t where t.name = 'A');
insert into rating.rating_supp_template(code,name) select 'B','B' from dual
where not exists (select 1 from rating.rating_supp_template t where t.name = 'B');
insert into rating.rating_supp_template(code,name) select 'C','C' from dual
where not exists (select 1 from rating.rating_supp_template t where t.name = 'C');
insert into rating.rating_supp_template(code,name) select 'D','D' from dual
where not exists (select 1 from rating.rating_supp_template t where t.name = 'D');


insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = '62e7d685-de66-4b85-b401-b5c69c836030')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and option_id = (select id from rating.rating_supp_options where code = '62e7d685-de66-4b85-b401-b5c69c836030'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = 'eadb13de-f617-4f4f-8c3c-9f755ddc663c')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and option_id = (select id from rating.rating_supp_options where code = 'eadb13de-f617-4f4f-8c3c-9f755ddc663c'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = 'f8bd4c60-c4cd-40a4-b13a-a8349bf66a24')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and option_id = (select id from rating.rating_supp_options where code = 'f8bd4c60-c4cd-40a4-b13a-a8349bf66a24'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = '7ccafc20-d860-4adc-8ad0-5f926a56bf61')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and option_id = (select id from rating.rating_supp_options where code = '7ccafc20-d860-4adc-8ad0-5f926a56bf61'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = 'cf84cd1d-62c4-433a-9b08-f85cd25c20e5')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and option_id = (select id from rating.rating_supp_options where code = 'cf84cd1d-62c4-433a-9b08-f85cd25c20e5'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = 'b7f8079c-8310-461c-ae4c-c63eb63dc9f6')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and option_id = (select id from rating.rating_supp_options where code = 'b7f8079c-8310-461c-ae4c-c63eb63dc9f6'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = '72cece1e-09ad-4bb9-9c7c-32465412da4e')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and option_id = (select id from rating.rating_supp_options where code = '72cece1e-09ad-4bb9-9c7c-32465412da4e'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = '7d51f7da-02e4-4850-b71a-996661f8861a')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and option_id = (select id from rating.rating_supp_options where code = '7d51f7da-02e4-4850-b71a-996661f8861a'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '62e7d685-de66-4b85-b401-b5c69c836030')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and option_id = (select id from rating.rating_supp_options where code = '62e7d685-de66-4b85-b401-b5c69c836030'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = 'eadb13de-f617-4f4f-8c3c-9f755ddc663c')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and option_id = (select id from rating.rating_supp_options where code = 'eadb13de-f617-4f4f-8c3c-9f755ddc663c'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = 'f8bd4c60-c4cd-40a4-b13a-a8349bf66a24')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and option_id = (select id from rating.rating_supp_options where code = 'f8bd4c60-c4cd-40a4-b13a-a8349bf66a24'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '7ccafc20-d860-4adc-8ad0-5f926a56bf61')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and option_id = (select id from rating.rating_supp_options where code = '7ccafc20-d860-4adc-8ad0-5f926a56bf61'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = 'cf84cd1d-62c4-433a-9b08-f85cd25c20e5')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and option_id = (select id from rating.rating_supp_options where code = 'cf84cd1d-62c4-433a-9b08-f85cd25c20e5'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = 'b7f8079c-8310-461c-ae4c-c63eb63dc9f6')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and option_id = (select id from rating.rating_supp_options where code = 'b7f8079c-8310-461c-ae4c-c63eb63dc9f6'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '72cece1e-09ad-4bb9-9c7c-32465412da4e')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and option_id = (select id from rating.rating_supp_options where code = '72cece1e-09ad-4bb9-9c7c-32465412da4e'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '7d51f7da-02e4-4850-b71a-996661f8861a')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and option_id = (select id from rating.rating_supp_options where code = '7d51f7da-02e4-4850-b71a-996661f8861a'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '3aeb5d80-ec23-46c2-b24e-d3f9a05ab076')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and option_id = (select id from rating.rating_supp_options where code = '3aeb5d80-ec23-46c2-b24e-d3f9a05ab076'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = 'f63773ea-cc76-4ede-af42-46285ba0959a')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and option_id = (select id from rating.rating_supp_options where code = 'f63773ea-cc76-4ede-af42-46285ba0959a'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '2d1b01c9-e9e6-40d6-b1ec-d4517d6298a7')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and option_id = (select id from rating.rating_supp_options where code = '2d1b01c9-e9e6-40d6-b1ec-d4517d6298a7'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '50df5443-e051-4bef-916c-9994f9ee9859')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and option_id = (select id from rating.rating_supp_options where code = '50df5443-e051-4bef-916c-9994f9ee9859'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '1e50cb11-8e7f-475c-9099-ed439e8674ad')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and option_id = (select id from rating.rating_supp_options where code = '1e50cb11-8e7f-475c-9099-ed439e8674ad'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '1c4abcae-e1e1-4605-b5b2-996f0829e7e7')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and option_id = (select id from rating.rating_supp_options where code = '1c4abcae-e1e1-4605-b5b2-996f0829e7e7'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = 'cc38460e-6ffa-469e-b44c-2cc03115c926')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and option_id = (select id from rating.rating_supp_options where code = 'cc38460e-6ffa-469e-b44c-2cc03115c926'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = 'a8a10a0c-9195-40c9-bb11-c410ab611372')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and option_id = (select id from rating.rating_supp_options where code = 'a8a10a0c-9195-40c9-bb11-c410ab611372'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '5994e4cd-6de9-473a-a199-c91c94073222')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and option_id = (select id from rating.rating_supp_options where code = '5994e4cd-6de9-473a-a199-c91c94073222'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = 'c63727b6-4e57-4b9d-9d51-cc8a90d9f72c')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and option_id = (select id from rating.rating_supp_options where code = 'c63727b6-4e57-4b9d-9d51-cc8a90d9f72c'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '178d2802-8e54-460c-9fa3-a29b0377c4c8')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and option_id = (select id from rating.rating_supp_options where code = '178d2802-8e54-460c-9fa3-a29b0377c4c8'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = 'fd49cfcf-2d6e-423b-b36a-27b05b6a5b30')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and option_id = (select id from rating.rating_supp_options where code = 'fd49cfcf-2d6e-423b-b36a-27b05b6a5b30'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '06ade6a9-12f5-417c-b161-cdc59519b8ed')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and option_id = (select id from rating.rating_supp_options where code = '06ade6a9-12f5-417c-b161-cdc59519b8ed'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '3cd9360d-9e97-4eb3-b6b8-85966abc2673')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and option_id = (select id from rating.rating_supp_options where code = '3cd9360d-9e97-4eb3-b6b8-85966abc2673'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = 'fa428765-09d0-478e-902d-acbe2947e4ae')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and option_id = (select id from rating.rating_supp_options where code = 'fa428765-09d0-478e-902d-acbe2947e4ae'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '6bead800-3481-4e5a-9fd3-1b89b93b105b')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and option_id = (select id from rating.rating_supp_options where code = '6bead800-3481-4e5a-9fd3-1b89b93b105b'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '1e50cb11-8e7f-475c-9099-ed439e8674ad')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and option_id = (select id from rating.rating_supp_options where code = '1e50cb11-8e7f-475c-9099-ed439e8674ad'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '1c4abcae-e1e1-4605-b5b2-996f0829e7e7')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and option_id = (select id from rating.rating_supp_options where code = '1c4abcae-e1e1-4605-b5b2-996f0829e7e7'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = 'cc38460e-6ffa-469e-b44c-2cc03115c926')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and option_id = (select id from rating.rating_supp_options where code = 'cc38460e-6ffa-469e-b44c-2cc03115c926'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = 'a8a10a0c-9195-40c9-bb11-c410ab611372')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and option_id = (select id from rating.rating_supp_options where code = 'a8a10a0c-9195-40c9-bb11-c410ab611372'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '5994e4cd-6de9-473a-a199-c91c94073222')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and option_id = (select id from rating.rating_supp_options where code = '5994e4cd-6de9-473a-a199-c91c94073222'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = 'c63727b6-4e57-4b9d-9d51-cc8a90d9f72c')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and option_id = (select id from rating.rating_supp_options where code = 'c63727b6-4e57-4b9d-9d51-cc8a90d9f72c'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '178d2802-8e54-460c-9fa3-a29b0377c4c8')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and option_id = (select id from rating.rating_supp_options where code = '178d2802-8e54-460c-9fa3-a29b0377c4c8'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = 'fd49cfcf-2d6e-423b-b36a-27b05b6a5b30')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and option_id = (select id from rating.rating_supp_options where code = 'fd49cfcf-2d6e-423b-b36a-27b05b6a5b30'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '06ade6a9-12f5-417c-b161-cdc59519b8ed')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and option_id = (select id from rating.rating_supp_options where code = '06ade6a9-12f5-417c-b161-cdc59519b8ed'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '3cd9360d-9e97-4eb3-b6b8-85966abc2673')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and option_id = (select id from rating.rating_supp_options where code = '3cd9360d-9e97-4eb3-b6b8-85966abc2673'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = 'fa428765-09d0-478e-902d-acbe2947e4ae')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and option_id = (select id from rating.rating_supp_options where code = 'fa428765-09d0-478e-902d-acbe2947e4ae'));
insert into rating.rating_supp_tmpl_option(supp_tmpl_id,option_id) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '6bead800-3481-4e5a-9fd3-1b89b93b105b')  from dual where not exists (select 1 from rating.rating_supp_tmpl_option where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and option_id = (select id from rating.rating_supp_options where code = '6bead800-3481-4e5a-9fd3-1b89b93b105b'));

insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = '62e7d685-de66-4b85-b401-b5c69c836030'),13.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and supp_option_id = (select id from rating.rating_supp_options where code = '62e7d685-de66-4b85-b401-b5c69c836030'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = 'eadb13de-f617-4f4f-8c3c-9f755ddc663c'),13.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and supp_option_id = (select id from rating.rating_supp_options where code = 'eadb13de-f617-4f4f-8c3c-9f755ddc663c'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = 'f8bd4c60-c4cd-40a4-b13a-a8349bf66a24'),11.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and supp_option_id = (select id from rating.rating_supp_options where code = 'f8bd4c60-c4cd-40a4-b13a-a8349bf66a24'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = '7ccafc20-d860-4adc-8ad0-5f926a56bf61'),11.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and supp_option_id = (select id from rating.rating_supp_options where code = '7ccafc20-d860-4adc-8ad0-5f926a56bf61'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = 'cf84cd1d-62c4-433a-9b08-f85cd25c20e5'),13.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and supp_option_id = (select id from rating.rating_supp_options where code = 'cf84cd1d-62c4-433a-9b08-f85cd25c20e5'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = 'b7f8079c-8310-461c-ae4c-c63eb63dc9f6'),13.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and supp_option_id = (select id from rating.rating_supp_options where code = 'b7f8079c-8310-461c-ae4c-c63eb63dc9f6'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = '72cece1e-09ad-4bb9-9c7c-32465412da4e'),13.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and supp_option_id = (select id from rating.rating_supp_options where code = '72cece1e-09ad-4bb9-9c7c-32465412da4e'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'A'), (select id from rating.rating_supp_options where code = '7d51f7da-02e4-4850-b71a-996661f8861a'),13.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'A') and supp_option_id = (select id from rating.rating_supp_options where code = '7d51f7da-02e4-4850-b71a-996661f8861a'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '62e7d685-de66-4b85-b401-b5c69c836030'),13.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and supp_option_id = (select id from rating.rating_supp_options where code = '62e7d685-de66-4b85-b401-b5c69c836030'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = 'eadb13de-f617-4f4f-8c3c-9f755ddc663c'),13.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and supp_option_id = (select id from rating.rating_supp_options where code = 'eadb13de-f617-4f4f-8c3c-9f755ddc663c'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = 'f8bd4c60-c4cd-40a4-b13a-a8349bf66a24'),11.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and supp_option_id = (select id from rating.rating_supp_options where code = 'f8bd4c60-c4cd-40a4-b13a-a8349bf66a24'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '7ccafc20-d860-4adc-8ad0-5f926a56bf61'),11.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and supp_option_id = (select id from rating.rating_supp_options where code = '7ccafc20-d860-4adc-8ad0-5f926a56bf61'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = 'cf84cd1d-62c4-433a-9b08-f85cd25c20e5'),13.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and supp_option_id = (select id from rating.rating_supp_options where code = 'cf84cd1d-62c4-433a-9b08-f85cd25c20e5'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = 'b7f8079c-8310-461c-ae4c-c63eb63dc9f6'),13.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and supp_option_id = (select id from rating.rating_supp_options where code = 'b7f8079c-8310-461c-ae4c-c63eb63dc9f6'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '72cece1e-09ad-4bb9-9c7c-32465412da4e'),13.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and supp_option_id = (select id from rating.rating_supp_options where code = '72cece1e-09ad-4bb9-9c7c-32465412da4e'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '7d51f7da-02e4-4850-b71a-996661f8861a'),13.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and supp_option_id = (select id from rating.rating_supp_options where code = '7d51f7da-02e4-4850-b71a-996661f8861a'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '3aeb5d80-ec23-46c2-b24e-d3f9a05ab076'),40.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and supp_option_id = (select id from rating.rating_supp_options where code = '3aeb5d80-ec23-46c2-b24e-d3f9a05ab076'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = 'f63773ea-cc76-4ede-af42-46285ba0959a'),20.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and supp_option_id = (select id from rating.rating_supp_options where code = 'f63773ea-cc76-4ede-af42-46285ba0959a'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '2d1b01c9-e9e6-40d6-b1ec-d4517d6298a7'),20.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and supp_option_id = (select id from rating.rating_supp_options where code = '2d1b01c9-e9e6-40d6-b1ec-d4517d6298a7'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'B'), (select id from rating.rating_supp_options where code = '50df5443-e051-4bef-916c-9994f9ee9859'),20.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'B') and supp_option_id = (select id from rating.rating_supp_options where code = '50df5443-e051-4bef-916c-9994f9ee9859'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '1e50cb11-8e7f-475c-9099-ed439e8674ad'),15.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and supp_option_id = (select id from rating.rating_supp_options where code = '1e50cb11-8e7f-475c-9099-ed439e8674ad'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '1c4abcae-e1e1-4605-b5b2-996f0829e7e7'),15.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and supp_option_id = (select id from rating.rating_supp_options where code = '1c4abcae-e1e1-4605-b5b2-996f0829e7e7'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = 'cc38460e-6ffa-469e-b44c-2cc03115c926'),15.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and supp_option_id = (select id from rating.rating_supp_options where code = 'cc38460e-6ffa-469e-b44c-2cc03115c926'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = 'a8a10a0c-9195-40c9-bb11-c410ab611372'),10.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and supp_option_id = (select id from rating.rating_supp_options where code = 'a8a10a0c-9195-40c9-bb11-c410ab611372'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '5994e4cd-6de9-473a-a199-c91c94073222'),10.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and supp_option_id = (select id from rating.rating_supp_options where code = '5994e4cd-6de9-473a-a199-c91c94073222'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = 'c63727b6-4e57-4b9d-9d51-cc8a90d9f72c'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and supp_option_id = (select id from rating.rating_supp_options where code = 'c63727b6-4e57-4b9d-9d51-cc8a90d9f72c'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '178d2802-8e54-460c-9fa3-a29b0377c4c8'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and supp_option_id = (select id from rating.rating_supp_options where code = '178d2802-8e54-460c-9fa3-a29b0377c4c8'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = 'fd49cfcf-2d6e-423b-b36a-27b05b6a5b30'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and supp_option_id = (select id from rating.rating_supp_options where code = 'fd49cfcf-2d6e-423b-b36a-27b05b6a5b30'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '06ade6a9-12f5-417c-b161-cdc59519b8ed'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and supp_option_id = (select id from rating.rating_supp_options where code = '06ade6a9-12f5-417c-b161-cdc59519b8ed'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '3cd9360d-9e97-4eb3-b6b8-85966abc2673'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and supp_option_id = (select id from rating.rating_supp_options where code = '3cd9360d-9e97-4eb3-b6b8-85966abc2673'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = 'fa428765-09d0-478e-902d-acbe2947e4ae'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and supp_option_id = (select id from rating.rating_supp_options where code = 'fa428765-09d0-478e-902d-acbe2947e4ae'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'C'), (select id from rating.rating_supp_options where code = '6bead800-3481-4e5a-9fd3-1b89b93b105b'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'C') and supp_option_id = (select id from rating.rating_supp_options where code = '6bead800-3481-4e5a-9fd3-1b89b93b105b'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '1e50cb11-8e7f-475c-9099-ed439e8674ad'),15.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and supp_option_id = (select id from rating.rating_supp_options where code = '1e50cb11-8e7f-475c-9099-ed439e8674ad'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '1c4abcae-e1e1-4605-b5b2-996f0829e7e7'),15.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and supp_option_id = (select id from rating.rating_supp_options where code = '1c4abcae-e1e1-4605-b5b2-996f0829e7e7'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = 'cc38460e-6ffa-469e-b44c-2cc03115c926'),15.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and supp_option_id = (select id from rating.rating_supp_options where code = 'cc38460e-6ffa-469e-b44c-2cc03115c926'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = 'a8a10a0c-9195-40c9-bb11-c410ab611372'),10.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and supp_option_id = (select id from rating.rating_supp_options where code = 'a8a10a0c-9195-40c9-bb11-c410ab611372'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '5994e4cd-6de9-473a-a199-c91c94073222'),10.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and supp_option_id = (select id from rating.rating_supp_options where code = '5994e4cd-6de9-473a-a199-c91c94073222'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = 'c63727b6-4e57-4b9d-9d51-cc8a90d9f72c'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and supp_option_id = (select id from rating.rating_supp_options where code = 'c63727b6-4e57-4b9d-9d51-cc8a90d9f72c'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '178d2802-8e54-460c-9fa3-a29b0377c4c8'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and supp_option_id = (select id from rating.rating_supp_options where code = '178d2802-8e54-460c-9fa3-a29b0377c4c8'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = 'fd49cfcf-2d6e-423b-b36a-27b05b6a5b30'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and supp_option_id = (select id from rating.rating_supp_options where code = 'fd49cfcf-2d6e-423b-b36a-27b05b6a5b30'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '06ade6a9-12f5-417c-b161-cdc59519b8ed'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and supp_option_id = (select id from rating.rating_supp_options where code = '06ade6a9-12f5-417c-b161-cdc59519b8ed'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '3cd9360d-9e97-4eb3-b6b8-85966abc2673'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and supp_option_id = (select id from rating.rating_supp_options where code = '3cd9360d-9e97-4eb3-b6b8-85966abc2673'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = 'fa428765-09d0-478e-902d-acbe2947e4ae'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and supp_option_id = (select id from rating.rating_supp_options where code = 'fa428765-09d0-478e-902d-acbe2947e4ae'));
insert into rating.rating_supp_tmpl_option_weight(supp_tmpl_id,supp_option_id,weight) select (select id from rating.rating_supp_template where name = 'D'), (select id from rating.rating_supp_options where code = '6bead800-3481-4e5a-9fd3-1b89b93b105b'),5.00 from dual where not exists (select 1 from rating.rating_supp_tmpl_option_weight where supp_tmpl_id = (select id from rating.rating_supp_template where name = 'D') and supp_option_id = (select id from rating.rating_supp_options where code = '6bead800-3481-4e5a-9fd3-1b89b93b105b'));


insert into rating.sys_authority(code,name) select 'AU_SYS_MGMT','系统管理' from dual where not exists (select 1 from rating.sys_authority where code = 'AU_SYS_MGMT');
insert into rating.sys_authority(code,name) select 'AU_USER_MGMT','用户管理' from dual where not exists (select 1 from rating.sys_authority where code = 'AU_USER_MGMT');
insert into rating.sys_authority(code,name) select 'AU_RATING_MGMT','投票管理' from dual where not exists (select 1 from rating.sys_authority where code = 'AU_RATING_MGMT');
insert into rating.sys_authority(code,name) select 'AU_RATING','投票权限' from dual where not exists (select 1 from rating.sys_authority where code = 'AU_RATING');
insert into rating.sys_authority(code,name) select 'AU_RATING_VOTE','参与投票' from dual where not exists (select 1 from rating.sys_authority where code = 'AU_RATING_VOTE');
insert into rating.sys_authority(code,name) select 'AU_RATING_STATISTICS','投票统计' from dual where not exists (select 1 from rating.sys_authority where code = 'AU_RATING_STATISTICS');
insert into rating.sys_authority(code,name) select 'AU_GROUP_MGMT','组/部门管理' from dual where not exists (select 1 from rating.sys_authority where code = 'AU_GROUP_MGMT');

insert into rating.sys_operation(code,name) select 'MGMT','管理' from dual
where not exists (select 1 from rating.sys_operation  where code = 'MGMT');

insert into rating.sys_resource(code,name,url,parent_code,seq) select 'SYS_MGMT','系统管理','system',null,1.00 from dual where not exists (select 1 from rating.sys_resource where code = 'SYS_MGMT');
insert into rating.sys_resource(code,name,url,parent_code,seq) select 'USER_MGMT','用户管理','system/user','SYS_MGMT',1.20 from dual where not exists (select 1 from rating.sys_resource where code = 'USER_MGMT');
insert into rating.sys_resource(code,name,url,parent_code,seq) select 'RATING_MGMT','投票管理','system/rating','SYS_MGMT',1.30 from dual where not exists (select 1 from rating.sys_resource where code = 'RATING_MGMT');
insert into rating.sys_resource(code,name,url,parent_code,seq) select 'RATING','投票','rating',null,2.00 from dual where not exists (select 1 from rating.sys_resource where code = 'RATING');
insert into rating.sys_resource(code,name,url,parent_code,seq) select 'RATING_VOTE','参与投票','rating','RATING',2.01 from dual where not exists (select 1 from rating.sys_resource where code = 'RATING_VOTE');
insert into rating.sys_resource(code,name,url,parent_code,seq) select 'RATING_STATISTICS','投票统计','rating/statistics','RATING',2.02 from dual where not exists (select 1 from rating.sys_resource where code = 'RATING_STATISTICS');
insert into rating.sys_resource(code,name,url,parent_code,seq) select 'GROUP_MGMT','组管理','system/group','SYS_MGMT',1.10 from dual where not exists (select 1 from rating.sys_resource where code = 'GROUP_MGMT');

insert into rating.sys_res_au_opr_mapping(res_code,auth_code,opr_code) select 'SYS_MGMT','AU_SYS_MGMT','MGMT' from dual where not exists (select 1 from rating.sys_res_au_opr_mapping where res_code = 'SYS_MGMT' AND auth_code = 'AU_SYS_MGMT');
insert into rating.sys_res_au_opr_mapping(res_code,auth_code,opr_code) select 'USER_MGMT','AU_USER_MGMT','MGMT' from dual where not exists (select 1 from rating.sys_res_au_opr_mapping where res_code = 'USER_MGMT' AND auth_code = 'AU_USER_MGMT');
insert into rating.sys_res_au_opr_mapping(res_code,auth_code,opr_code) select 'RATING_MGMT','AU_RATING_MGMT','MGMT' from dual where not exists (select 1 from rating.sys_res_au_opr_mapping where res_code = 'RATING_MGMT' AND auth_code = 'AU_RATING_MGMT');
insert into rating.sys_res_au_opr_mapping(res_code,auth_code,opr_code) select 'RATING','AU_RATING','MGMT' from dual where not exists (select 1 from rating.sys_res_au_opr_mapping where res_code = 'RATING' AND auth_code = 'AU_RATING');
insert into rating.sys_res_au_opr_mapping(res_code,auth_code,opr_code) select 'RATING_VOTE','AU_RATING_VOTE','MGMT' from dual where not exists (select 1 from rating.sys_res_au_opr_mapping where res_code = 'RATING_VOTE' AND auth_code = 'AU_RATING_VOTE');
insert into rating.sys_res_au_opr_mapping(res_code,auth_code,opr_code) select 'RATING_STATISTICS','AU_RATING_STATISTICS','MGMT' from dual where not exists (select 1 from rating.sys_res_au_opr_mapping where res_code = 'RATING_STATISTICS' AND auth_code = 'AU_RATING_STATISTICS');
insert into rating.sys_res_au_opr_mapping(res_code,auth_code,opr_code) select 'GROUP_MGMT','AU_GROUP_MGMT','MGMT' from dual where not exists (select 1 from rating.sys_res_au_opr_mapping where res_code = 'GROUP_MGMT' AND auth_code = 'AU_GROUP_MGMT');

insert into rating.sys_role(name) select '管理员' from dual
where not exists (select 1 from rating.sys_role where name = '管理员');

insert into rating.sys_role(name) select 'DEFAULT' from dual
where not exists (select 1 from rating.sys_role where name = 'DEFAULT');

insert into rating.sys_role_auth_mapping(role_id,auth_id) select (select id from rating.sys_role where name ='管理员'),(SELECT id FROM rating.sys_authority where code = 'AU_SYS_MGMT') from dual where not exists (select 1 from rating.sys_role_auth_mapping where role_id = (select id from rating.sys_role where name ='管理员') and auth_id = (SELECT id FROM rating.sys_authority where code = 'AU_SYS_MGMT'));
insert into rating.sys_role_auth_mapping(role_id,auth_id) select (select id from rating.sys_role where name ='管理员'),(SELECT id FROM rating.sys_authority where code = 'AU_USER_MGMT') from dual where not exists (select 1 from rating.sys_role_auth_mapping where role_id = (select id from rating.sys_role where name ='管理员') and auth_id = (SELECT id FROM rating.sys_authority where code = 'AU_USER_MGMT'));
insert into rating.sys_role_auth_mapping(role_id,auth_id) select (select id from rating.sys_role where name ='管理员'),(SELECT id FROM rating.sys_authority where code = 'AU_RATING_MGMT') from dual where not exists (select 1 from rating.sys_role_auth_mapping where role_id = (select id from rating.sys_role where name ='管理员') and auth_id = (SELECT id FROM rating.sys_authority where code = 'AU_RATING_MGMT'));
insert into rating.sys_role_auth_mapping(role_id,auth_id) select (select id from rating.sys_role where name ='管理员'),(SELECT id FROM rating.sys_authority where code = 'AU_RATING_STATISTICS') from dual where not exists (select 1 from rating.sys_role_auth_mapping where role_id = (select id from rating.sys_role where name ='管理员') and auth_id = (SELECT id FROM rating.sys_authority where code = 'AU_RATING_STATISTICS'));
insert into rating.sys_role_auth_mapping(role_id,auth_id) select (select id from rating.sys_role where name ='管理员'),(SELECT id FROM rating.sys_authority where code = 'AU_GROUP_MGMT') from dual where not exists (select 1 from rating.sys_role_auth_mapping where role_id = (select id from rating.sys_role where name ='管理员') and auth_id = (SELECT id FROM rating.sys_authority where code = 'AU_GROUP_MGMT'));
insert into rating.sys_role_auth_mapping(role_id,auth_id) select (select id from rating.sys_role where name ='DEFAULT'),(SELECT id FROM rating.sys_authority where code = 'AU_RATING_VOTE') from dual where not exists (select 1 from rating.sys_role_auth_mapping where role_id = (select id from rating.sys_role where name ='DEFAULT') and auth_id = (SELECT id FROM rating.sys_authority where code = 'AU_RATING_VOTE'));

insert into rating.sys_user(username,salt,password,name,status) select 'admin','123456','ea48576f30be1669971699c09ad05c94','管理员',0 from dual
where not exists (select 1 from rating.sys_user where username = 'admin');

insert into rating.sys_user_role(role_id,user_id) select 
(select id from rating.sys_role where name ='管理员'),
(select id from rating.sys_user where username='admin') from dual
where not exists (select 1 from rating.sys_user_role where role_id = 
(select id from rating.sys_role where name ='管理员') 
and user_id = (select id from rating.sys_user where username='admin'));

commit;